### ISSUE TITLE
How connect facebook in your app

### ISSUE THREAD

**Issue by johnfelipe** [Dhanush123/Facebook-Wall-Personality-Insights#3]
![solved](https://cloud.githubusercontent.com/assets/428820/19628690/311b6ac6-9929-11e6-9dd3-89b40184c339.png)

Pls tell me how solve that

**Comment by Dhanush123** [comment]
Hi @johnfelipe, sorry for the really late reply! If you're still interested in resolving this issue, I will say that I didn't mention in the readme that you need to setup an app at developers.facebook.com and then put in your own Facebook app credentials into the code provided in this repo. Hope that helps :)
