### ISSUE TITLE
Clarification: Reset Facebook user

### ISSUE THREAD

**Issue by baricks** [Dhanush123/Facebook-Wall-Personality-Insights#4]
This is a really great repo! While getting it up and running, I didn't see a button/way to reset the page so that a new user can sign into Facebook. How do you do that?

**Comment by Dhanush123** [comment]
Hi @baricks thank you! The solution to your question is change data-auto-logout-link from ="false" to ="true" in index.ejs. Hope that helps :)

**Comment by baricks** [comment]
@Dhanush123 Perfect, that did it! Thanks for the quick response :)

**Comment by baricks** [comment]
@Dhanush123 Is it possible to have other users log in with their Facebook information or do they need to have a developer account set up to do so?

**Comment by Dhanush123** [comment]
@baricks sorry for the late reply. Once Facebook approves your app through the FB dev console/site, then anyone with a FB account can use it. Until then you can add people, such as testers, through the roles tab in your FB app.
![screen shot 2017-06-26 at 11 54 44 pm](https://user-images.githubusercontent.com/7054987/27574369-eeddf9e4-5aca-11e7-9420-7d5256c16dd4.png)

**Comment by baricks** [comment]
Thank you!!
